[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[features]
default = []
debug-log = []

[dependencies]
once_cell = "1.19"
dashmap = "6.1.0"
parking_lot = "0.12"
lasso = { version = "0.7.3", features = ["multi-threaded"] }
walkdir = "2"

thiserror = { workspace = true }
tracing-log = { workspace = true }

jclass = { path = "../jclass" }
jimage = { path = "../jimage" }
common = { path = "../common" }

# TODO to be deleted
toml = "0.8"
log = "0.4.27"
